# Generated by Django 5.1.6 on 2025-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_service_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала брони'),
        ),
    ]
