services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: Reservation
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: 2000c08o09Cyny
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "reservation_user", "-d",
              "Reservation", "-h", "localhost", "-p", "5432" ]
      retries: 1
      start_period: 1s

  web:
    build: .
    command: poetry run gunicorn reservation_service_API.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
